-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 18:00:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pms_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pms_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pms_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pms_db` ;

-- -----------------------------------------------------
-- Table `pms_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pms_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pms_db`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pms_db`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_constraint_name` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_constraint_name`
    FOREIGN KEY (`user_id`)
    REFERENCES `pms_db`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pms_db`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pms_db`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_type` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `priority` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `due_date` DATE NOT NULL,
  `project_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_project` (`project_id` ASC) VISIBLE,
  INDEX `fk_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `pms_db`.`projects` (`id`),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `pms_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pms_db`.`task_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pms_db`.`task_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `content` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_task` (`task_id` ASC) VISIBLE,
  INDEX `fk_userr` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `pms_db`.`tasks` (`id`),
  CONSTRAINT `fk_userr`
    FOREIGN KEY (`user_id`)
    REFERENCES `pms_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
